### ISSUE TITLE
Unable to start normally

### ISSUE THREAD

**Issue by BlueFlyDev** [AllayMC/Allay#243]
[09:05:58 INFO] [main] [AllayAPI] Server language was set to English (United States)
[09:05:59 INFO] [main] [Allay] Starting Allay...
[09:05:59 INFO] [main] [ComponentClassCacheUtils] Class cache is loaded
[09:05:59 INFO] [main] [AllayEnchantmentRegistry] Loading enchantment types...
[09:06:00 INFO] [main] [AllayEnchantmentRegistry] Loaded 38 enchantment types
[09:06:00 INFO] [main] [AllayVanillaItemAttributeRegistry] Start loading vanilla item attribute data registry...
[09:06:00 INFO] [main] [AllayVanillaItemAttributeRegistry] Loaded vanilla item attribute data registry successfully
[09:06:00 INFO] [main] [AllayItemTypeRegistry] Loading item types...
[09:06:03 INFO] [main] [AllayItemTypeRegistry] Loaded 1568 item types
[09:06:03 INFO] [main] [AllayBlockEntityTypeRegistry] Loading block entity types...
[09:06:03 INFO] [main] [AllayBlockEntityTypeRegistry] Loaded 2 block entity types
[09:06:03 INFO] [main] [AllayVanillaBlockAttributeRegistry] Start loading vanilla block attribute data registry...
[09:06:04 INFO] [main] [AllayVanillaBlockAttributeRegistry] Loaded vanilla block attribute data registry successfully
[09:06:04 INFO] [main] [AllayBlockTypeRegistry] Loading block types...
[09:06:07 INFO] [main] [AllayBlockTypeRegistry] Loaded 1078 block types
[09:06:07 INFO] [main] [AllayEffectRegistry] Loading effect types...
[09:06:07 INFO] [main] [AllayEffectRegistry] Loaded 30 effect types
[09:06:07 INFO] [main] [AllayEntityTypeRegistry] Loading entity types...
[09:06:08 INFO] [main] [AllayEntityTypeRegistry] Loaded 122 entity types
[09:06:08 INFO] [main] [AllayCreativeItemRegistry] Loading creative items...
[09:06:08 INFO] [main] [AllayCreativeItemRegistry] Creative items is loaded
[09:06:08 INFO] [main] [AllayPackRegistry] Pack auto encrypting is enabled, encryption is starting...
[09:06:08 INFO] [main] [AllayPackRegistry] Loading packs...
[09:06:08 INFO] [main] [AllayPackRegistry] Loaded 0 packs
[09:06:08 INFO] [main] [AllayAPI] This server is running Allay, implement Allay-API version 1.0.0
[09:06:08 INFO] [main] [AllayWorldPool] Loading world world
[09:06:09 INFO] [main] [AllayWorldPool] World world is loaded
[09:06:09 INFO] [main] [AllayServer] Starting up network server...
[09:06:09 INFO] [main] [AllayServer] Network server started at 127.0.0.1:19132 (11576 ms)
[09:06:09 ERROR] [main] [Allay] Error while starting the server!
java.lang.NegativeArraySizeException: -1
	at org.allaymc.server.gui.Dashboard.updatePluginTable(Dashboard.java:377) ~[Allay-Server-1.0.0-all.jar:?]
	at org.allaymc.server.gui.Dashboard.serverStarted(Dashboard.java:324) ~[Allay-Server-1.0.0-all.jar:?]
	at org.allaymc.server.AllayServer.start(AllayServer.java:194) ~[Allay-Server-1.0.0-all.jar:?]
	at org.allaymc.server.Allay.main(Allay.java:105) [Allay-Server-1.0.0-all.jar:?]

**Comment by smartcmd** [comment]
fixed
